name: Coverage
on:
  push:
    branches:
      - "*"

jobs:
  collect_coverage:
    runs-on: ubuntu-latest
    env:
      IS_CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage/clover.xml